config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  resources :orders
  resources :line_items
  devise_for :users
  root 'storefront#all_items'

  get 'category' => 'storefront#items_by_category'

  get 'brand' => 'storefront#items_by_brand'

  resources :products

  get 'products' => 'products#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecomerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
    
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fa fa-home"></i> Mincazon
        <% end %>
      </div>
​
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

		Choose Brand<span class="caret"></span></a>
          	<ul class="dropdown-menu">
          		<% @brands.each do |brand| %>
          			<li>
          				<%= link_to brand, brand_path(name: brand) %>
          			</li>
          		<% end %>
          	</ul>
          </li>
          <li class="dropdown">
          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Choose Category<span class="caret"></span></a>
          	<ul class="dropdown-menu">
          		<% @categories.each do |category| %>
          			<li>
          				<%= link_to category.name, category_path(id: category.id) %>
          			</li>
          		<% end %>
          	</ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
        	<li class="shoppin"> <%= link_to "", view_order_path, class:"glyphicon glyphicon-shopping-cart", style:"color:white" %>
        	<p>
        	<% if @line_items.count == 0 %>
        	Empty
        	<% else %>
        	(<%=@line_items.count%>)
        	<% end %>
        	</p>
        	</li>

        </ul>


        
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
           <li> <span><%= link_to "Edit Profile", edit_user_registration_path, class:"devise" %></span></li>
            <li> <span><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"devise" %></span></li>
            <% else %>
 
  			<li> <span><%= link_to "Login", new_user_session_path, class:"devise"  %></span> </li>
  			</span>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
 
  </nav>


	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<div class="container">
<%= yield %>
</div>



<footer>
		<p> &copy; 2016 Mincazon </p>
	</footer>
</body>
</html>